[build-system]
requires = ["hatchling>=1.27.0"]
build-backend = "hatchling.build"

[project]
name = "vs_align"
version = "3.3.1"
description = "Video Alignment and Synchronization for VapourSynth."
readme = "README.md"
requires-python = ">=3.12"
authors = [{ name = "pifroggi" }]
license = "MIT"
license-files = ["LICENSE"]

keywords = [
	"vapoursynth",
	"video",
	"alignment",
	"synchronization",
	"filtering"
]

classifiers = [
	"Programming Language :: Python :: 3",
	"Topic :: Multimedia :: Video",
    "Environment :: GPU",
]

dependencies = [
	"vapoursynth",
    "opencv-python",
	"numpy",
]

[project.urls]
Homepage = "https://github.com/pifroggi/vs_align"
Repository = "https://github.com/pifroggi/vs_align"
Issues = "https://github.com/pifroggi/vs_align/issues"
